rewards:
    zeus:
        lightning: $x $y $z
    tp:
        tp: $x $y $z
    day:
        time: 0
    cookies:
        give: COOKIE 5
    fullheal:
        heal: 20
altars:
    GOLD_BLOCK:
        gifts:
            DIAMOND_SWORD:
                reward: zeus
            CAKE:
                reward: cookies
            CLAY_BALL:
                reward: fullheal
            WATCH:
                amount: 3
                reward: day
            SLIME_BALL:
                reward: tp
decay: true
click-type: LEFT
